// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duakxtwqzvsplbczxzyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1YWt4dHdxenZzcGxiY3p4enl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDc5MjEsImV4cCI6MjA2MzMyMzkyMX0.xjvsG3BCIt18Lk9Q3D65gE6xoDvRpfOvgVqub881brc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);